name: Build

on:
  workflow_dispatch:
    inputs:
      build_plan:
        description: 'Build plans name'
        required: true
        default: 'IosvekaCustom'
      build_targets:
        description: 'Build targets (contents,ttf,ttf-unhinted)'
        required: true
        default: 'contents'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm ttfautohint fontforge python3-pip git zip gh

      - name: Run build script
        id: run_build
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          chmod +x run.sh
          ./run.sh "${{ github.event.inputs.build_plan }}" "${{ github.event.inputs.build_targets }}"
          RELEASE_TAG=$(python3 -c "import tomllib; print(tomllib.load(open('config/workflow.toml','rb'))['release_tag'])")
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          echo "ZIP_FILE=${RELEASE_TAG}.zip" >> $GITHUB_ENV

      - name: Upload zip to artifact
        uses: actions/upload-artifact@v4
        with:
          name: fonts
          path: "${{ github.workspace }}/${{ env.ZIP_FILE }}"

      - name: Create GitHub Release and upload zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.RELEASE_TAG }}"
          name: "Iosevka Build ${{ github.event.inputs.build_plan }}"
          files: "${{ github.workspace }}/${{ env.ZIP_FILE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}