name: Build

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: "Build target (contents, ttf, ttf-unhinted)"
        required: true
        default: "ttf"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        id: cache-node
        uses: actions/cache@v4
        with:
          path: Iosevka/node_modules
          key: ${{ runner.os }}-iosevka-${{ hashFiles('private-build-plans.toml') }}
          restore-keys: |
            ${{ runner.os }}-iosevka-

      - name: Setup deps (cache miss)
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: bash setup.sh

      - name: Run build
        run: bash build.sh ${{ github.event.inputs.build_target }}

      - name: Prepare update.md
        run: |
          echo "### Build Log" > update.md
          date +"%Y-%m-%d %H:%M:%S" >> update.md
          echo -e "\n\`\`\`toml" >> update.md
          cat private-build-plans.toml >> update.md
          echo -e "\`\`\`" >> update.md

      - name: Push to output branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/output; then
            git checkout output
            rm -rf *
          else
            git checkout --orphan output
          fi
          cp output/IosevkaCustom.zip .
          cp update.md .
          git add .
          git commit -m "Update build $(date)"
          git push origin output --force

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/IosevkaCustom.zip
          tag_name: ${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
          body_path: update.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}