name: Build

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: "Build target (contents, ttf, ttf-unhinted)"
        required: true
        default: "contents"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        id: cache-node
        uses: actions/cache@v4
        with:
          path: Iosevka/node_modules
          key: ${{ runner.os }}-iosevka-${{ hashFiles('Iosevka/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-iosevka-

      - name: Setup deps (cache miss)
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: bash setup.sh

      - name: Run build
        run: bash build.sh ${{ github.event.inputs.build_target }}

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          echo "### Build Log" > artifacts/update.md
          date -u +"%Y-%m-%d %H:%M:%S UTC" >> artifacts/update.md
          echo -e "\n\`\`\`toml" >> artifacts/update.md
          cat private-build-plans.toml >> artifacts/update.md
          echo -e "\`\`\`" >> artifacts/update.md

          mv IosevkaCustom.zip artifacts/

      - name: Push build results to update branch
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          rm -rf update

          git fetch origin update || true

          if git show-ref --verify --quiet refs/remotes/origin/update; then
            git checkout update --
            find . -mindepth 1 -not -path './.git*' -exec rm -rf {} +
          else
            git checkout --orphan update
            git rm -rf . || true
          fi

          cp -r artifacts/* .

          git add -A
          git commit -m "Update build $(date -u +"%Y-%m-%d %H:%M:%S UTC")" || echo "No changes to commit"

          if ! git ls-remote --exit-code origin update >/dev/null 2>&1; then
            echo "[INFO] Branch 'update' belum ada di remote, membuat baru..."
            git push origin update
          else
            echo "[INFO] Branch 'update' sudah ada, melakukan force push..."
            git push origin update --force
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/IosevkaCustom.zip
          tag_name: ${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
          body_path: artifacts/update.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}