name: Build Iosevka

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install zip & gh
        run: sudo apt-get update && sudo apt-get install -y zip gh

      - name: Upload ZIP to artifact
        uses: actions/upload-artifact@v4
        with:
          name: fonts
          path: ${{ env.ZIP_FILE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Build ${{ env.RELEASE_TAG }}"
          files: ${{ env.ZIP_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}