name: Build Iosevka Custom

on:
  workflow_dispatch:
    inputs:
      build_plan:
        description: 'Nama build plan'
        required: true
        default: 'IosvekaCustom'
      build_targets:
        description: 'Target build (pisahkan koma, contoh: contents,ttf,ttf-unhinted)'
        required: true
        default: 'contents'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Run setup + build
        run: |
          chmod +x run.sh
          ./run.sh "${{ github.event.inputs.build_plan }}" "${{ github.event.inputs.build_targets }}"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fonts-${{ github.event.inputs.build_plan }}
          path: Iosevka/dist/*