name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install zip & gh
        run: sudo apt-get update && sudo apt-get install -y zip gh
      - name: Run build.sh
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          chmod +x build.sh
          ./build.sh "${{ inputs.build_plan }}" "${{ inputs.build_targets }}"
      - name: Upload artifact & release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: "Build ${{ env.RELEASE_TAG }}"
          files: ${{ env.ZIP_FILE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}