name: Build Iosevka Custom

on:
  workflow_dispatch:
    inputs:
      build_plan:
        description: 'Nama build plan (sesuai di private-build-plans.toml)'
        required: true
        default: 'IosvekaCustom'
      build_targets:
        description: 'Target build (pisahkan dengan koma, contoh: contents,ttf,unhinted)'
        required: true
        default: 'contents'
      release_tag:
        description: 'Tag untuk Release'
        required: true
        default: 'custom-build'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm ttfautohint fontforge python3-pip
          npm install -g pnpm

      - name: Clone Iosevka source
        run: |
          git clone --depth=1 https://github.com/be5invis/Iosevka.git
          cp private-build-plans.toml Iosevka/private-build-plans.toml

      - name: Install build deps
        working-directory: Iosevka
        run: |
          pnpm install

      - name: Run build
        working-directory: Iosevka
        run: |
          IFS=',' read -ra TARGETS <<< "${{ github.event.inputs.build_targets }}"
          for target in "${TARGETS[@]}"; do
            echo "➡️ Building $target::${{ github.event.inputs.build_plan }}"
            pnpm build --targets $target::${{ github.event.inputs.build_plan }}
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fonts
          path: Iosevka/dist/*

      - name: Delete old release if exists
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          name: "Iosevka Custom ${{ github.event.inputs.release_tag }}"
          files: Iosevka/dist/*