name: Run Build

on:
  workflow_dispatch:
    inputs:
      build_plan:
        description: 'Build plan name'
        required: true
        default: 'IosevkaCustom'
      build_targets:
        description: 'Build targets (contents,ttf,ttf-unhinted)'
        required: true
        default: 'contents'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check dependencies
        id: check_deps
        run: |
          if [ ! -d "Iosevka" ] || [ ! -d "Iosevka/node_modules" ]; then
            echo "needs_setup=true" >> $GITHUB_OUTPUT
          else
            echo "needs_setup=false" >> $GITHUB_OUTPUT
      - name: Run setup if needed
        if: steps.check_deps.outputs.needs_setup == 'true'
        uses: ./.github/workflows/setup.yml
      - name: Run build
        uses: ./.github/workflows/build.yml
        with:
          build_plan: ${{ github.event.inputs.build_plan }}
          build_targets: ${{ github.event.inputs.build_targets }}