name: Run Build

on:
  workflow_dispatch:
    inputs:
      build_plan:
        description: 'Build plan name'
        required: true
        default: 'IosevkaCustom'
      build_targets:
        description: 'Build targets (contents,ttf,ttf-unhinted)'
        required: true
        default: 'contents'

jobs:
  check-and-setup:
    runs-on: ubuntu-latest
    outputs:
      setup_done: ${{ steps.set_output.outputs.setup_done }}
    steps:
      - uses: actions/checkout@v4

      - name: Check dependencies
        id: check_deps
        run: |
          if [ ! -d "Iosevka" ] || [ ! -d "Iosevka/node_modules" ]; then
            echo "needs_setup=true" >> $GITHUB_OUTPUT
          else
            echo "needs_setup=false" >> $GITHUB_OUTPUT
          fi

      - name: Run setup if needed
        id: set_output
        run: |
          if [ "${{ steps.check_deps.outputs.needs_setup }}" == "true" ]; then
            echo "Running setup.sh..."
            chmod +x setup.sh
            ./setup.sh
            echo "setup_done=true" >> $GITHUB_OUTPUT
          else
            echo "Setup not needed"
            echo "setup_done=false" >> $GITHUB_OUTPUT
          fi