name: Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('Iosevka/package-lock.json') }}
          restore-keys: |
            npm-cache-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm ttfautohint fontforge python3-pip git zip

      - name: Clone Iosevka
        run: |
          if [ ! -d "Iosevka" ]; then
            git clone --depth=1 https://github.com/be5invis/Iosevka.git
            cp ./config/private-build-plans.toml Iosevka/private-build-plans.toml

      - name: Install npm deps
        working-directory: Iosevka
        run: npm install